#!/usr/bin/env bash

declare -ra operating_systems=( linux osx win )
declare -r framework=netcoreapp2.1
declare -r architecture=x64

for os in ${operating_systems[@]}; do
    runtime=$os-$architecture
    output=target/lib/$framework/$runtime
    dotnet publish --configuration Debug --framework $framework --runtime $runtime --self-contained --output $output
done
