#!/usr/bin/env bash

declare -r script_root="$(cd "$(dirname "$1")" && pwd)"
set -o errexit -o nounset

case $1 in
cosmos)
    declare -r test_case=cosmos
    declare -r authority="cosmos-sdk-cassandra:obMFvyk4rPKevxVVLEkTLCPnCP0PlDL26N7e0MFTYxZMuKixcaMdpwiSxM1mQIpZCk5wpDacVh2NGU8zaLPJXw==@cosmos-sdk-cassandra.cassandra.cosmos.azure.com:10350"
    declare -r ssl="--ssl"
    ;;
cosmosproxy)
    declare -r test_case=cosmosproxy
    declare -r authority="cosmos-sdk-cassandra:obMFvyk4rPKevxVVLEkTLCPnCP0PlDL26N7e0MFTYxZMuKixcaMdpwiSxM1mQIpZCk5wpDacVh2NGU8zaLPJXw==@localhost:9042"
    ;;
localcassandra)
    declare -r test_case=localcassandra
    declare -r authority="localhost:9142"
    declare -r ssl="--ssl"
    ;;
esac

for workload in insert read; do
    "${script_root}/../driver-tests/stress/bin/stress" ${workload} --authority "${authority}" -n 1000 --report-file "${script_root}/test.${test_case}.csv" ${ssl:-}
done
