#!/usr/bin/env bash

declare -r script_root="$(cd "$(dirname "$1")" && pwd)"
declare -r service_home=$(ls -d ~/local/opt/azure-cosmosdb-cassandra-gateway-*)

JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStore='$service_home/etc/azure-cosmosdb-cassandra-gateway.truststore.PKCS12' -Djavax.net.ssl.trustStorePassword=cassandra.localproxy -Djavax.net.ssl.trustStoreType=PKCS12" \
"${service_home}/bin/azure-cosmosdb-cassandra-gateway"
