#!/usr/bin/env bash

declare -r script_root="$(cd "$(dirname "$1")" && pwd)"
declare -r service_home=$(ls -d ~/local/opt/azure-cosmosdb-cassandra-gateway-*)

JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStore='$HOME/local/opt/cassandra/conf/cassandra-truststore.PKCS12' -Djavax.net.ssl.trustStorePassword=cassandra.local -Djavax.net.ssl.trustStoreType=PKCS12" \
"${service_home}/bin/azure-cosmosdb-cassandra-gateway"
